name: Train, Register, and Deploy Model

permissions:
  contents: write

on:
  push:
    branches: [UAT, main]
  workflow_dispatch:

jobs:
  Train_Model:
    name: Train_Model
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Configure Databricks CLI
        run: |
          mkdir -p ~/.databricks
          echo "[DEFAULT]" > ~/.databricks/config
          echo "host = $DATABRICKS_HOST" >> ~/.databricks/config
          echo "token = $DATABRICKS_TOKEN" >> ~/.databricks/config

      - name: Trigger Databricks Job
        run: |
          databricks jobs run-now --job-id 480467520180602 \
          --notebook-params '{
            "SNOWFLAKE_ACCOUNT": "${{ secrets.SNOWFLAKE_ACCOUNT }}",
            "SNOWFLAKE_USER": "${{ secrets.SNOWFLAKE_USER }}",
            "SNOWFLAKE_PASSWORD": "${{ secrets.SNOWFLAKE_PASSWORD }}",
            "SNOWFLAKE_WAREHOUSE": "${{ secrets.SNOWFLAKE_WAREHOUSE }}",
            "SNOWFLAKE_DATABASE": "${{ secrets.SNOWFLAKE_DATABASE }}"
          }'